### ISSUE TITLE
I suspect g1 and h1 should be different.

### ISSUE THREAD

**Issue by gdanezis** [asonnino/coconut#1]
Furthemore, they should have an unknown representation with respect to each other. So use a hash-to-point to get h1 = hash("some fixed string").

https://github.com/asonnino/coconut/blob/44d20b98e1de98e31b931c495f4462374ca6060e/coconut/lib.py#L14-L15

**Comment by asonnino** [comment]
Yes this was for testing at the beginning, I am implementing now the multi-messages scheme and then replacing that line with this:
```hs = [G.hashG1(("h%s" % i).encode("utf8")) for i in range(q)]```
